### PR TITLE
Code coverage tool added

### PR DESCRIPTION
**Pull request by yaoandrew**

### CODE REVIEW

**Comment by catmclough** [comment]
For future reference, if you're working on two stories that don't rely on eachother, it's best to branch them both off of master. That way, if changes are made in the other branch during the peer review process, this branch won't have to continually be updated. In addition, it keeps the pull requests clean so that code not having to do with the code coverage tool doesn't show up in the diff.

**Comment by catmclough** [comment]
When I run the tests in this branch I get the following error: `/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in require: cannot load such file -- simplecov (LoadError)`

If there's anything the user has to install, would you add that to the README?

**Comment by yaoandrew** [comment]
Sure.. I think you need to run bundle install but I'll add that to the
readme.

**Comment by catmclough** [comment]
:'(

**Pull request closed without merging**
